"""empty message

Revision ID: 002299601dc7
Revises: 283f016e078a
Create Date: 2025-01-11 18:04:16.333113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002299601dc7'
down_revision = '283f016e078a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image2', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('image3', sa.String(length=500), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.create_unique_constraint(None, ['image2'])
        batch_op.create_unique_constraint(None, ['image3'])
        batch_op.create_unique_constraint(None, ['image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.drop_column('image3')
        batch_op.drop_column('image2')

    # ### end Alembic commands ###
