"""empty message

Revision ID: 15414b56e55c
Revises: 8ca599830e87
Create Date: 2024-10-21 22:43:33.917521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15414b56e55c'
down_revision = '8ca599830e87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('products_brand_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('products_brand_id_fkey', 'brands', ['brand_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
