"""empty message

Revision ID: 24113ca64b39
Revises: 002299601dc7
Create Date: 2025-01-28 18:12:45.647758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24113ca64b39'
down_revision = '002299601dc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=500), nullable=True))
        batch_op.create_unique_constraint(None, ['image'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_category', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
