"""empty message

Revision ID: 508f74babb02
Revises: ea205935f8e6
Create Date: 2025-03-25 23:22:59.979876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '508f74babb02'
down_revision = 'ea205935f8e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('isAvailable',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('isAvailable',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
