"""empty message

Revision ID: a412bdce63e6
Revises: 0faa65b5e123
Create Date: 2025-03-11 23:30:02.931094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a412bdce63e6'
down_revision = '0faa65b5e123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isAvailable', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('isAvailable')

    # ### end Alembic commands ###
